require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe V1::Admin::UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # V1::Admin::User. As you add validations to V1::Admin::User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # V1::Admin::UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all v1_admin_users as @v1_admin_users" do
      user = V1::Admin::User.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:v1_admin_users)).to eq([user])
    end
  end

  describe "GET #show" do
    it "assigns the requested v1_admin as @v1_admin" do
      user = V1::Admin::User.create! valid_attributes
      get :show, params: {id: user.to_param}, session: valid_session
      expect(assigns(:v1_admin)).to eq(user)
    end
  end

  describe "GET #new" do
    it "assigns a new v1_admin as @v1_admin" do
      get :new, params: {}, session: valid_session
      expect(assigns(:v1_admin)).to be_a_new(V1::Admin::User)
    end
  end

  describe "GET #edit" do
    it "assigns the requested v1_admin as @v1_admin" do
      user = V1::Admin::User.create! valid_attributes
      get :edit, params: {id: user.to_param}, session: valid_session
      expect(assigns(:v1_admin)).to eq(user)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new V1::Admin::User" do
        expect {
          post :create, params: {v1_admin: valid_attributes}, session: valid_session
        }.to change(V1::Admin::User, :count).by(1)
      end

      it "assigns a newly created v1_admin as @v1_admin" do
        post :create, params: {v1_admin: valid_attributes}, session: valid_session
        expect(assigns(:v1_admin)).to be_a(V1::Admin::User)
        expect(assigns(:v1_admin)).to be_persisted
      end

      it "redirects to the created v1_admin" do
        post :create, params: {v1_admin: valid_attributes}, session: valid_session
        expect(response).to redirect_to(V1::Admin::User.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved v1_admin as @v1_admin" do
        post :create, params: {v1_admin: invalid_attributes}, session: valid_session
        expect(assigns(:v1_admin)).to be_a_new(V1::Admin::User)
      end

      it "re-renders the 'new' template" do
        post :create, params: {v1_admin: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested v1_admin" do
        user = V1::Admin::User.create! valid_attributes
        put :update, params: {id: user.to_param, v1_admin: new_attributes}, session: valid_session
        user.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested v1_admin as @v1_admin" do
        user = V1::Admin::User.create! valid_attributes
        put :update, params: {id: user.to_param, v1_admin: valid_attributes}, session: valid_session
        expect(assigns(:v1_admin)).to eq(user)
      end

      it "redirects to the v1_admin" do
        user = V1::Admin::User.create! valid_attributes
        put :update, params: {id: user.to_param, v1_admin: valid_attributes}, session: valid_session
        expect(response).to redirect_to(user)
      end
    end

    context "with invalid params" do
      it "assigns the v1_admin as @v1_admin" do
        user = V1::Admin::User.create! valid_attributes
        put :update, params: {id: user.to_param, v1_admin: invalid_attributes}, session: valid_session
        expect(assigns(:v1_admin)).to eq(user)
      end

      it "re-renders the 'edit' template" do
        user = V1::Admin::User.create! valid_attributes
        put :update, params: {id: user.to_param, v1_admin: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested v1_admin" do
      user = V1::Admin::User.create! valid_attributes
      expect {
        delete :destroy, params: {id: user.to_param}, session: valid_session
      }.to change(V1::Admin::User, :count).by(-1)
    end

    it "redirects to the v1_admin_users list" do
      user = V1::Admin::User.create! valid_attributes
      delete :destroy, params: {id: user.to_param}, session: valid_session
      expect(response).to redirect_to(v1_admin_users_url)
    end
  end

end
